apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-actix-api
  namespace: vshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: product-actix-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: product-actix
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: product-actix-api
    spec:
      containers:
      - name: product-actix-api
        image: product-actix:latest
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "mysql://root:YourPass@mysql:3306/vshop"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8080"
        resources:
          limits:
            memory: "128Mi"
            cpu: "128m"
        ports:
        - containerPort: 8080
