apiVersion: v1
kind: Service
metadata:
  name: product-actix-api
  namespace: vshop
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: product-actix-api
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32000
